# Generated by Django 5.0.2 on 2024-03-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Semestre')),
                ('status', models.CharField(choices=[('active', 'Vigente'), ('draft', 'No Publicado'), ('expired', 'Antiguo')], default='draft', max_length=10, verbose_name='Estado')),
                ('start', models.DateField(verbose_name='Comienza')),
                ('end', models.DateField(verbose_name='Comienza')),
                ('correlative', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'db_table': 'sumate_semestre',
            },
        ),
    ]
