# Generated by Django 5.0.2 on 2024-03-07 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semester', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(verbose_name='Total de Puntos Descontados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('executed_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executed_semesters', to='semester.semester', verbose_name='Semestre Ejecutado')),
                ('expired_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expired_semesters', to='semester.semester', verbose_name='Semestre Expirado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Punto Expirado',
                'verbose_name_plural': 'Puntos Expirados',
                'db_table': 'sumate_expired_points',
            },
        ),
    ]
