# Generated by Django 5.0.2 on 2024-03-17 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expiredpoints',
            table='sumate_puntos_expirados',
        ),
    ]
