# Generated by Django 5.0.2 on 2024-03-07 14:17

import apps.prize.models.prize
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semester', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Premio')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.prize.models.prize.prize_image_file_path, verbose_name='Imagen')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('points', models.IntegerField(verbose_name='Puntos necesarios')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
            ],
            options={
                'verbose_name': 'Premio',
                'verbose_name_plural': 'Premios',
                'db_table': 'sumate_premio',
            },
        ),
        migrations.CreateModel(
            name='PrizeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Puntos Gastados')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Canje')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('status', models.CharField(choices=[('hold', 'Reservado'), ('delivered', 'Entregado'), ('canceled', 'Cancelado'), ('expired', 'Expirado')], default='hold', max_length=20, verbose_name='Estado')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize', to='prize.prize', verbose_name='Premio')),
                ('provided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provided_by', to=settings.AUTH_USER_MODEL, verbose_name='Entregado Por')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemption_semester', to='semester.semester', verbose_name='Canjeado el Semestre')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='Canjeado Por')),
            ],
            options={
                'verbose_name': 'Canje',
                'verbose_name_plural': 'Canjes',
                'db_table': 'sumate_premio_canje',
            },
        ),
    ]
