# Generated by Django 5.0.2 on 2024-09-27 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
