# Generated by Django 5.0.2 on 2024-03-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shift',
            field=models.CharField(choices=[('D', 'Diurno'), ('V', 'Vespertino'), ('N', 'Sin información')], default='D', max_length=1, verbose_name='Jornada'),
        ),
    ]
