# Generated by Django 5.0.2 on 2024-09-27 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_enrolled', models.PositiveIntegerField(verbose_name='Total Matriculados')),
                ('semester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enroll', to='semester.semester')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'db_table': 'enroll',
            },
        ),
    ]
